version: 2.1

jobs:
  test:
    docker:
      - image: shaguarger/platformio
    steps:
      - checkout
      - run:
          command: |
            cd control-panel
            platformio check --skip-packages --environment megaatmega2560

  build:
    docker:
      - image: shaguarger/platformio
    steps:
      - checkout
      - run:
          command: |
            cd control-panel
            platformio run --environment megaatmega2560
      - persist_to_workspace:
          root: control-panel/.pio/build/megaatmega2560
          paths:
            - firmware.elf
            - firmware.hex
      - store_artifacts:
          path: control-panel/.pio/build/megaatmega2560/firmware.elf
          destination: firmware.elf
      - store_artifacts:
          path: control-panel/.pio/build/megaatmega2560/firmware.hex
          destination: firmware.hex

  release:
    docker:
      - image: cimg/base:2022.06
    environment:
      TAG: << pipeline.git.tag >>
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - attach_workspace:
          at: ${CIRCLE_WORKING_DIRECTORY}/control-panel/.pio/build/megaatmega2560
      - run:
          name: "Publish Release on GitHub"
          command: |
            docker run -it -e GITHUB_TOKEN=${GITHUB_TOKEN} maniator/gh:v2.20.0 "gh release create ${CIRCLECI_TAG} -t ${CIRCLE_PROJECT_REPONAME} firmware.hex firmware.elf"

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$*/
            branches:
              only: /.*/
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$*/
            branches:
              only: main
          requires:
            - test
      - release:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$*/
            branches:
              ignore: /.*/
          requires:
            - build
