---
name: Arduino

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    container: shaguarger/platformio

    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        cd control-panel
        platformio run --environment megaatmega2560 

  build:

    runs-on: ubuntu-latest
    needs: [test]
    if: contains('refs/heads/main', github.ref)

    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        cd control-panel
        platformio run --environment megaatmega2560 