---
name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install platform
        run: arduino-cli core install arduino:avr

      - name: Install dependencies
        run: arduino-cli lib install "LiquidCrystal I2C" SD

      - name: Compile Sketch
        working-directory: ./control-panel
        run: arduino-cli compile -b arduino:avr:mega:cpu=atmega2560 -e

      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
          name: control-panel
          path: ./control-panel/build/arduino.avr.mega/control-panel.ino.*
